### ISSUE TITLE
M1 macにqulacsが入らない件

### ISSUE THREAD

**Issue by sakurairihito** [sakurairihito/QCMaterialNew#20]
pip install qulacsを行うと以下のエラーが出る

```
$ pip install qulacs    
Collecting qulacs
  Using cached Qulacs-0.3.0.tar.gz (209 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: qulacs
  Building wheel for qulacs (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/sakurairihito/.julia/conda/3/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py'"'"'; __file__='"'"'/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-wheel-1dzte5aj
       cwd: /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/
  Complete output (277 lines):
  running bdist_wheel
  running build
  running build_ext
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as
  
      project(ProjectName)
  
    near the top of the file, but after cmake_minimum_required().
  
    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- The C compiler identification is AppleClang 13.1.6.13160021
  -- The CXX compiler identification is AppleClang 13.1.6.13160021
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/gcc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/g++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- SIMD SUPPORT: No
  -- CMAKE_HOST_SYSTEM_PROCESSOR = arm64
  -- USE_SIMD = No
  -- USE_OMP = Yes
  -- USE_GPU = No
  -- USE_TEST = Yes
  -- USE_PYTHON = Yes
  -- OPT_FLAGS = -mtune=native -march=native
  -- Fetch googletest for C++ testing
  CMake Deprecation Warning at build/temp.macosx-11.0-arm64-3.9/_deps/googletest_fetch-src/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at build/temp.macosx-11.0-arm64-3.9/_deps/googletest_fetch-src/googlemock/CMakeLists.txt:42 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at build/temp.macosx-11.0-arm64-3.9/_deps/googletest_fetch-src/googletest/CMakeLists.txt:49 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- Found PythonInterp: /Users/sakurairihito/.julia/conda/3/bin/python3.9 (found version "3.9.7")
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Fetch pybind11 for python-binding
  -- Found PythonLibs: /Users/sakurairihito/.julia/conda/3/lib/libpython3.9.dylib
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.5.0
  -- Install from pip
  -- OUTDIR = /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/lib.macosx-11.0-arm64-3.9
  -- CMAKE_SYSTEM_NAME = Darwin
  -- CMAKE_C_COMPILER = /usr/bin/gcc
  -- CMAKE_CXX_COMPILER = /usr/bin/g++
  -- CMAKE_BUILD_TYPE = Release
  -- CMAKE_CXX_FLAGS = -DVERSION_INFO=\"0.3.0\" -std=gnu++14 -pthread -fext-numeric-literals -fopenmp
  -- CMAKE_CXX_FLAGS_DEBUG = -g
  -- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG -mtune=native -march=native
  CMake Deprecation Warning at src/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at src/csim/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at src/cppsim/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at src/vqcsim/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at test/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at test/csim/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at test/cppsim/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at test/vqcsim/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at python/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Failed
  -- LTO disabled (not supported by the compiler and/or linker)
  CMake Warning (dev) at python/CMakeLists.txt:58 (target_link_libraries):
    Policy CMP0023 is not set: Plain and keyword target_link_libraries
    signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
    details.  Use the cmake_policy command to set the policy and suppress this
    warning.
  
    The keyword signature for target_link_libraries has already been used with
    the target "qulacs".  All uses of target_link_libraries with a target
    should be either all-keyword or all-plain.
  
    The uses of the keyword signature are here:
  
     * build/temp.macosx-11.0-arm64-3.9/_deps/pybind11_fetch-src/tools/pybind11Tools.cmake:179 (target_link_libraries)
  
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  CMake Deprecation Warning at benchmark/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- Configuring done
  CMake Warning (dev):
    Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
    --help-policy CMP0042" for policy details.  Use the cmake_policy command to
    set the policy and suppress this warning.
  
    MACOSX_RPATH is not specified for the following targets:
  
     cppsim_shared
     csim_shared
     vqcsim_shared
  
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:
  
      PYTHON_SETUP_FLAG
  
  
  -- Build files have been written to: /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9
  [  0%] Creating directories for 'eigen'
  [  0%] Performing download step (download, verify and extract) for 'eigen'
  -- Downloading...
     dst='/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9/eigen/src/eigen-3.3.7.tar.gz'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz'
  -- Downloading... done
  -- extracting...
       src='/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9/eigen/src/eigen-3.3.7.tar.gz'
       dst='/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9/eigen/src/eigen'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  [  2%] No update step for 'eigen'
  [  4%] No patch step for 'eigen'
  [  6%] No configure step for 'eigen'
  [  9%] No build step for 'eigen'
  [ 11%] Performing install step for 'eigen'
  [ 11%] No test step for 'eigen'
  [ 11%] Completed 'eigen'
  [ 11%] Built target eigen
  [ 11%] Building C object src/csim/CMakeFiles/csim_static.dir/constant.c.o
  [ 13%] Building C object src/csim/CMakeFiles/csim_static.dir/init_ops_fill.c.o
  clang: error: the clang compiler does not support '-march=native'
  clang: error: the clang compiler does not support '-march=native'
  clang: error: unsupported option '-fopenmp'
  clang: error: unsupported option '-fopenmp'
  make[3]: *** [src/csim/CMakeFiles/csim_static.dir/init_ops_fill.c.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  make[3]: *** [src/csim/CMakeFiles/csim_static.dir/constant.c.o] Error 1
  make[2]: *** [src/csim/CMakeFiles/csim_static.dir/all] Error 2
  make[1]: *** [CMakeFiles/python.dir/rule] Error 2
  make: *** [python] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py", line 110, in <module>
      setup(
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py", line 50, in run
      self.build_extension(ext)
    File "/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py", line 108, in build_extension
      subprocess.check_call(['cmake', '--build', '.', '--target', 'python'] + build_args, cwd=self.build_temp)
    File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'python', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for qulacs
  Running setup.py clean for qulacs
Failed to build qulacs
Installing collected packages: qulacs
    Running setup.py install for qulacs ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/sakurairihito/.julia/conda/3/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py'"'"'; __file__='"'"'/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-record-5kg2zvmd/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sakurairihito/.julia/conda/3/include/python3.9/qulacs
         cwd: /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/
    Complete output (281 lines):
    running install
    /Users/sakurairihito/.julia/conda/3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_ext
    CMake Warning (dev) in CMakeLists.txt:
      No project() command is present.  The top-level CMakeLists.txt file must
      contain a literal, direct call to the project() command.  Add a line of
      code such as
    
        project(ProjectName)
    
      near the top of the file, but after cmake_minimum_required().
    
      CMake is pretending there is a "project(Project)" command on the first
      line.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- The C compiler identification is AppleClang 13.1.6.13160021
    -- The CXX compiler identification is AppleClang 13.1.6.13160021
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/gcc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/g++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- SIMD SUPPORT: No
    -- CMAKE_HOST_SYSTEM_PROCESSOR = arm64
    -- USE_SIMD = No
    -- USE_OMP = Yes
    -- USE_GPU = No
    -- USE_TEST = Yes
    -- USE_PYTHON = Yes
    -- OPT_FLAGS = -mtune=native -march=native
    -- Fetch googletest for C++ testing
    CMake Deprecation Warning at build/temp.macosx-11.0-arm64-3.9/_deps/googletest_fetch-src/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at build/temp.macosx-11.0-arm64-3.9/_deps/googletest_fetch-src/googlemock/CMakeLists.txt:42 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at build/temp.macosx-11.0-arm64-3.9/_deps/googletest_fetch-src/googletest/CMakeLists.txt:49 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Found PythonInterp: /Users/sakurairihito/.julia/conda/3/bin/python3.9 (found version "3.9.7")
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Fetch pybind11 for python-binding
    -- Found PythonLibs: /Users/sakurairihito/.julia/conda/3/lib/libpython3.9.dylib
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.5.0
    -- Install from pip
    -- OUTDIR = /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/lib.macosx-11.0-arm64-3.9
    -- CMAKE_SYSTEM_NAME = Darwin
    -- CMAKE_C_COMPILER = /usr/bin/gcc
    -- CMAKE_CXX_COMPILER = /usr/bin/g++
    -- CMAKE_BUILD_TYPE = Release
    -- CMAKE_CXX_FLAGS = -DVERSION_INFO=\"0.3.0\" -std=gnu++14 -pthread -fext-numeric-literals -fopenmp
    -- CMAKE_CXX_FLAGS_DEBUG = -g
    -- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG -mtune=native -march=native
    CMake Deprecation Warning at src/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at src/csim/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at src/cppsim/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at src/vqcsim/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at test/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at test/csim/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at test/cppsim/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at test/vqcsim/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    CMake Deprecation Warning at python/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Failed
    -- LTO disabled (not supported by the compiler and/or linker)
    CMake Warning (dev) at python/CMakeLists.txt:58 (target_link_libraries):
      Policy CMP0023 is not set: Plain and keyword target_link_libraries
      signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
      details.  Use the cmake_policy command to set the policy and suppress this
      warning.
    
      The keyword signature for target_link_libraries has already been used with
      the target "qulacs".  All uses of target_link_libraries with a target
      should be either all-keyword or all-plain.
    
      The uses of the keyword signature are here:
    
       * build/temp.macosx-11.0-arm64-3.9/_deps/pybind11_fetch-src/tools/pybind11Tools.cmake:179 (target_link_libraries)
    
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Deprecation Warning at benchmark/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Configuring done
    CMake Warning (dev):
      Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
      --help-policy CMP0042" for policy details.  Use the cmake_policy command to
      set the policy and suppress this warning.
    
      MACOSX_RPATH is not specified for the following targets:
    
       cppsim_shared
       csim_shared
       vqcsim_shared
    
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        PYTHON_SETUP_FLAG
    
    
    -- Build files have been written to: /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9
    [  0%] Creating directories for 'eigen'
    [  0%] Performing download step (download, verify and extract) for 'eigen'
    -- Downloading...
       dst='/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9/eigen/src/eigen-3.3.7.tar.gz'
       timeout='none'
       inactivity timeout='none'
    -- Using src='https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz'
    -- Downloading... done
    -- extracting...
         src='/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9/eigen/src/eigen-3.3.7.tar.gz'
         dst='/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/build/temp.macosx-11.0-arm64-3.9/eigen/src/eigen'
    -- extracting... [tar xfz]
    -- extracting... [analysis]
    -- extracting... [rename]
    -- extracting... [clean up]
    -- extracting... done
    [  2%] No update step for 'eigen'
    [  4%] No patch step for 'eigen'
    [  6%] No configure step for 'eigen'
    [  9%] No build step for 'eigen'
    [ 11%] Performing install step for 'eigen'
    [ 11%] No test step for 'eigen'
    [ 11%] Completed 'eigen'
    [ 11%] Built target eigen
    [ 11%] Building C object src/csim/CMakeFiles/csim_static.dir/constant.c.o
    [ 13%] Building C object src/csim/CMakeFiles/csim_static.dir/init_ops_fill.c.o
    clang: error: the clang compiler does not support '-march=native'
    clang: clang: error: unsupported option '-fopenmp'
    error: the clang compiler does not support '-march=native'
    clang: error: unsupported option '-fopenmp'
    make[3]: *** [src/csim/CMakeFiles/csim_static.dir/init_ops_fill.c.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    make[3]: *** [src/csim/CMakeFiles/csim_static.dir/constant.c.o] Error 1
    make[2]: *** [src/csim/CMakeFiles/csim_static.dir/all] Error 2
    make[1]: *** [CMakeFiles/python.dir/rule] Error 2
    make: *** [python] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py", line 110, in <module>
        setup(
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py", line 50, in run
        self.build_extension(ext)
      File "/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py", line 108, in build_extension
        subprocess.check_call(['cmake', '--build', '.', '--target', 'python'] + build_args, cwd=self.build_temp)
      File "/Users/sakurairihito/.julia/conda/3/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'python', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sakurairihito/.julia/conda/3/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py'"'"'; __file__='"'"'/private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-install-6pj7mc_z/qulacs_e720006711cc4632b0363c38756a79fc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/p2/d5ppcv5d5g55w17wgl79ltkm0000gn/T/pip-record-5kg2zvmd/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sakurairihito/.julia/conda/3/include/python3.9/qulacs Check the logs for full command output.

```

**Comment by sakurairihito** [comment]
以下の記事を参考にしたら、インストール完了できた。
https://qiita.com/akiraichi5430/items/d9b700457af66a109110

gitから直接qulacsをインストールすればよかったっぽい

**Comment by sakurairihito** [comment]
Qulacsのissuesに書いてあった。バグが起きたらissuesをチェックすべし
